import * as stylex from "@stylexjs/stylex";

const paletteIn = stylex.keyframes({
  from: { opacity: 0, transform: "scale(0.9)" },
  to: { opacity: 1, transform: "scale(1)" },
});

export const appearanceStyles = stylex.create({
  panel: {
    boxSizing: "border-box",
    position: "relative",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.085)",
    borderRadius: 24,
    backgroundColor: "rgba(18, 17, 24, 0.72)",
    boxShadow: "0 20px 60px rgba(0, 0, 0, 0.16), inset 0 1px 0 rgba(255, 255, 255, 0.035)",
    backdropFilter: "blur(28px) saturate(120%)",
    padding: {
      default: "27px 22px 36px",
      "@media (max-width: 640px)": "24px 18px",
    },
    overflowY: "auto",
    display: {
      default: "block",
      "@media (max-width: 820px)": "grid",
      "@media (max-width: 640px)": "block",
    },
    gridTemplateColumns: { "@media (max-width: 820px)": "repeat(2, minmax(0, 1fr))" },
    gap: { "@media (max-width: 820px)": "0 28px" },
    borderTopColor: { "@media (max-width: 820px)": "rgba(255, 255, 255, 0.08)" },
    borderLeftWidth: { "@media (max-width: 820px)": 0 },
  },
  fullWidth: { gridColumn: { "@media (max-width: 820px)": "1 / -1" } },
  heading: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  headingTitle: { margin: 0, fontSize: 18, fontWeight: 590, letterSpacing: "-0.02em" },
  headingText: { margin: "4px 0 0", color: "#77737f", fontSize: 13 },
  group: {
    marginTop: 10,
    padding: 15,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.075)",
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.025)",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.018)",
  },
  label: {
    minHeight: 22,
    marginBottom: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    color: "#c9c7ce",
    fontSize: 13,
    fontWeight: 520,
  },
  labelValue: { color: "#73737f", fontSize: 12, fontWeight: 500 },
  paletteExpand: {
    boxSizing: "border-box",
    appearance: "none",
    display: "flex",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: 999,
    padding: "4px 7px",
    color: "#73737f",
    backgroundColor: "transparent",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 500,
    fontFamily: "inherit",
    transition: "color 140ms ease",
    ":hover": {
      color: { "@media (hover: hover) and (pointer: fine)": "#aaa6b2" },
      borderColor: {
        "@media (hover: hover) and (pointer: fine)": "rgba(255, 255, 255, 0.08)",
      },
      backgroundColor: {
        "@media (hover: hover) and (pointer: fine)": "rgba(255, 255, 255, 0.035)",
      },
    },
    ":focus-visible": {
      outlineWidth: 2,
      outlineStyle: "solid",
      outlineColor: "rgba(178, 168, 238, 0.85)",
      outlineOffset: 3,
    },
  },
  paletteExpandIcon: {
    width: 14,
    height: 14,
    transition: "transform 180ms cubic-bezier(0.23, 1, 0.32, 1)",
    "@media (prefers-reduced-motion: reduce)": { transform: "none" },
  },
  paletteExpandIconOpen: { transform: "rotate(180deg)" },
  paletteGrid: { display: "grid", gridTemplateColumns: "repeat(6, 1fr)", gap: 8 },
  palette: {
    boxSizing: "border-box",
    appearance: "none",
    height: 36,
    display: "grid",
    placeItems: "center",
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: 11,
    cursor: "pointer",
    color: "inherit",
    boxShadow: "inset 0 0 0 1px rgba(255, 255, 255, 0.11)",
    transition: "transform 140ms cubic-bezier(0.23, 1, 0.32, 1), filter 150ms ease",
    ":hover": { filter: { "@media (hover: hover) and (pointer: fine)": "brightness(1.08)" } },
    ":active": { transform: "scale(0.95)" },
    ":focus-visible": {
      outlineWidth: 2,
      outlineStyle: "solid",
      outlineColor: "rgba(178, 168, 238, 0.85)",
      outlineOffset: 3,
    },
    "@media (prefers-reduced-motion: reduce)": {
      transform: "none",
      transition: "opacity 160ms ease",
    },
  },
  paletteExtra: {
    animationName: paletteIn,
    animationDuration: "180ms",
    animationTimingFunction: "cubic-bezier(0.23, 1, 0.32, 1)",
  },
  paletteActive: {
    borderColor: "#f4f2f8",
    boxShadow:
      "0 0 0 2px rgba(17, 15, 27, 0.9), 0 0 0 3px rgba(196, 181, 253, 0.8), 0 7px 18px rgba(0, 0, 0, 0.22)",
  },
  paletteCheck: {
    width: 15,
    opacity: 1,
    filter: "drop-shadow(0 1px 2px rgba(0, 0, 0, 0.4))",
  },
  ratioGrid: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 8 },
  ratio: {
    boxSizing: "border-box",
    appearance: "none",
    height: 38,
    display: "grid",
    placeItems: "center",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 11,
    color: "#77737f",
    backgroundColor: "rgba(255, 255, 255, 0.025)",
    cursor: "pointer",
    fontSize: 10,
    fontWeight: 560,
    fontFamily: "inherit",
    transition:
      "transform 140ms cubic-bezier(0.23, 1, 0.32, 1), border-color 140ms ease, color 140ms ease, background-color 140ms ease",
    ":hover": {
      borderColor: { "@media (hover: hover) and (pointer: fine)": "rgba(255, 255, 255, 0.2)" },
      color: { "@media (hover: hover) and (pointer: fine)": "#aaa6b2" },
    },
    ":active": { transform: "scale(0.96)" },
    ":focus-visible": {
      outlineWidth: 2,
      outlineStyle: "solid",
      outlineColor: "rgba(178, 168, 238, 0.85)",
      outlineOffset: 3,
    },
    "@media (prefers-reduced-motion: reduce)": {
      transform: "none",
      transition: "opacity 160ms ease",
    },
  },
  ratioActive: {
    borderColor: "rgba(196, 181, 253, 0.72)",
    color: "#e8e3ff",
    backgroundColor: "rgba(143, 131, 223, 0.12)",
    boxShadow: "inset 0 0 0 1px rgba(196, 181, 253, 0.08)",
  },
  switchList: {
    marginTop: 10,
    paddingInline: 15,
    overflow: "hidden",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.075)",
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.025)",
  },
  switchItem: {
    minHeight: 64,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "rgba(255, 255, 255, 0.075)",
    cursor: "pointer",
  },
  switchItemLast: { borderBottomWidth: 0 },
  switchCopy: { display: "grid", gap: 2 },
  switchTitle: { color: "#d7d7dc", fontSize: 13, fontWeight: 580 },
  switchText: { color: "#696974", fontSize: 11 },
});
