import * as stylex from "@stylexjs/stylex";

export const appStyles = stylex.create({
  shell: {
    minHeight: "100vh",
    position: "relative",
    isolation: "isolate",
    overflow: "hidden",
    backgroundImage:
      "radial-gradient(circle at 16% 0%, rgba(99, 89, 156, 0.14), transparent 34%), linear-gradient(145deg, #0b0b10, #111019 58%, #0c0c12)",
  },
  resizing: {
    cursor: "ew-resize",
    userSelect: "none",
  },
  topbar: {
    boxSizing: "border-box",
    height: {
      default: 68,
      "@media (max-width: 640px)": 62,
    },
    paddingInline: {
      default: 24,
      "@media (max-width: 640px)": 15,
    },
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
    backgroundColor: "rgba(15, 14, 21, 0.64)",
    boxShadow: "inset 0 -1px 0 rgba(255, 255, 255, 0.02)",
    backdropFilter: "blur(24px) saturate(125%)",
    position: "relative",
    zIndex: 10,
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    color: "#f4f3f6",
    textDecoration: "none",
    fontSize: 16,
    fontWeight: 580,
    letterSpacing: "-0.018em",
  },
  brandMark: {
    boxSizing: "border-box",
    width: 31,
    height: 31,
    display: "grid",
    placeItems: "center",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.11)",
    borderRadius: 11,
    color: "#b2a8ee",
    backgroundImage:
      "linear-gradient(180deg, rgba(255, 255, 255, 0.08), rgba(255, 255, 255, 0.035))",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
  },
  topbarActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  utilityButton: {
    boxSizing: "border-box",
    height: { default: 36, "@media (max-width: 640px)": 34 },
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingInline: { default: 12, "@media (max-width: 640px)": 9 },
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 999,
    color: "#d1ced8",
    backgroundColor: "rgba(255, 255, 255, 0.045)",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.035)",
    backdropFilter: "blur(14px)",
    cursor: "pointer",
    font: "inherit",
    fontSize: 12,
    fontWeight: 520,
    transition:
      "background-color 160ms ease, border-color 160ms ease, color 160ms ease, transform 140ms cubic-bezier(0.23, 1, 0.32, 1), opacity 160ms ease",
    ":hover": {
      backgroundColor: "rgba(255, 255, 255, 0.075)",
      borderColor: "rgba(255, 255, 255, 0.15)",
      color: "#f5f3f8",
    },
    ":active": { transform: "scale(0.97)" },
    ":focus-visible": {
      outlineWidth: 2,
      outlineStyle: "solid",
      outlineColor: "rgba(178, 168, 238, 0.85)",
      outlineOffset: 3,
    },
    ":disabled": { cursor: "default", opacity: 0.38 },
    "@media (prefers-reduced-motion: reduce)": {
      transform: "none",
      transition: "opacity 160ms ease",
    },
  },
  utilityIcon: {
    width: 14,
    height: 14,
  },
  utilityLabel: {
    display: { default: "inline", "@media (max-width: 520px)": "none" },
  },
  workspace: {
    boxSizing: "border-box",
    minHeight: {
      default: "calc(100vh - 68px)",
      "@media (max-width: 640px)": "calc(100vh - 62px)",
    },
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 1fr) 328px",
      "@media (max-width: 820px)": "1fr",
    },
    gap: 14,
    padding: 14,
  },
});
