import * as stylex from "@stylexjs/stylex";

export const previewStyles = stylex.create({
  canvas: {
    minWidth: 0,
    padding: {
      default: "20px 22px 22px",
      "@media (max-width: 640px)": "14px 12px",
    },
    display: "flex",
    flexDirection: "column",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.075)",
    borderRadius: 24,
    backgroundImage:
      "linear-gradient(135deg, rgba(255, 255, 255, 0.035), rgba(255, 255, 255, 0.012))",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.025), 0 20px 60px rgba(0, 0, 0, 0.1)",
  },
  previewWrap: {
    flex: 1,
    display: { default: "grid", "@media (max-width: 820px)": "block" },
    placeItems: "center",
    minHeight: {
      default: 530,
      "@media (max-width: 820px)": 500,
      "@media (max-width: 640px)": 430,
    },
    overflow: { default: "auto", "@media (max-width: 820px)": "visible" },
    overflowX: { "@media (max-width: 820px)": "auto" },
  },
  stage: {
    maxWidth: "100%",
    minWidth: 520,
    position: "relative",
    overflow: "hidden",
    isolation: "isolate",
    opacity: 1,
    transform: "translateY(0)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 10,
    boxShadow: "0 24px 70px rgba(0, 0, 0, 0.24), inset 0 1px 0 rgba(255, 255, 255, 0.07)",
    transition:
      "opacity 220ms cubic-bezier(0.23, 1, 0.32, 1), transform 220ms cubic-bezier(0.23, 1, 0.32, 1)",
    marginInline: { "@media (max-width: 820px)": "auto" },
    "::before": {
      content: '""',
      position: "absolute",
      inset: 0,
      backgroundImage:
        "linear-gradient(145deg, rgba(255, 255, 255, 0.08), transparent 38%, rgba(0, 0, 0, 0.08))",
      zIndex: -1,
    },
    "@media (prefers-reduced-motion: reduce)": {
      transform: "none",
      transition: "opacity 160ms ease",
    },
  },
  indicator: {
    position: "absolute",
    bottom: 12,
    left: "50%",
    zIndex: 4,
    minWidth: 62,
    padding: "5px 9px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 7,
    opacity: 0,
    transform: "translate(-50%, 5px)",
    backgroundColor: "rgba(16, 15, 22, 0.78)",
    color: "rgba(244, 242, 248, 0.88)",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.06), 0 8px 24px rgba(0, 0, 0, 0.2)",
    backdropFilter: "blur(12px)",
    pointerEvents: "none",
    textAlign: "center",
    fontFamily: '"Geist Mono Variable", ui-monospace, monospace',
    fontSize: 11,
    transition: "opacity 140ms ease, transform 180ms cubic-bezier(0.23, 1, 0.32, 1)",
    "@media (prefers-reduced-motion: reduce)": {
      transform: "none",
      transition: "opacity 160ms ease",
    },
  },
  indicatorVisible: { opacity: 1, transform: "translate(-50%, 0)" },
  grain: {
    position: "absolute",
    inset: 0,
    zIndex: -1,
    opacity: 0.08,
    backgroundImage:
      "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.28'/%3E%3C/svg%3E\")",
  },
  codeWindow: {
    minHeight: 380,
    overflow: "hidden",
    position: "relative",
    boxShadow: "0 20px 45px rgba(0, 0, 0, 0.3), inset 0 0 0 1px rgba(255, 255, 255, 0.05)",
    transition: "border-radius 180ms cubic-bezier(0.23, 1, 0.32, 1), background-color 180ms ease",
    "@media (prefers-reduced-motion: reduce)": {
      transform: "none",
      transition: "opacity 160ms ease",
    },
  },
  windowReveal: {
    display: "grid",
    gridTemplateRows: "64px",
    overflow: "hidden",
    transition: "grid-template-rows 220ms cubic-bezier(0.77, 0, 0.175, 1)",
    "@media (prefers-reduced-motion: reduce)": {
      transform: "none",
      transition: "opacity 160ms ease",
    },
  },
  windowRevealHidden: { gridTemplateRows: "0px" },
  windowBar: {
    height: 64,
    position: "relative",
    display: "grid",
    gridTemplateColumns: "1fr auto 1fr",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "rgba(255, 255, 255, 0.045)",
    backgroundColor: "rgba(255, 255, 255, 0.015)",
    paddingInline: 23,
    transition: "opacity 160ms ease, transform 220ms cubic-bezier(0.77, 0, 0.175, 1)",
    "@media (prefers-reduced-motion: reduce)": {
      transform: "none",
      transition: "opacity 160ms ease",
    },
  },
  windowBarHidden: { opacity: 0, transform: "translateY(-8px)" },
  windowSide: { minWidth: 90 },
  traffic: { display: "flex", gap: 8 },
  trafficLight: {
    width: 11,
    height: 11,
    display: "block",
    borderRadius: "50%",
    boxShadow: "inset 0 0 0 1px rgba(0, 0, 0, 0.12)",
  },
  trafficRed: { backgroundColor: "#ff5f57" },
  trafficYellow: { backgroundColor: "#febc2e" },
  trafficGreen: { backgroundColor: "#28c840" },
  terminalGlyph: {
    fontFamily: '"Geist Mono Variable", ui-monospace, monospace',
    fontSize: 15,
    fontWeight: 620,
  },
  titleInput: {
    width: 210,
    borderWidth: 0,
    outline: "none",
    textAlign: "center",
    color: "#92909a",
    backgroundColor: "transparent",
    fontFamily: '"Geist Mono Variable", ui-monospace, monospace',
    fontSize: 12,
    ":focus": { color: "#fff" },
  },
  language: {
    justifySelf: "end",
    color: "#73717b",
    fontFamily: '"Geist Mono Variable", ui-monospace, monospace',
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: "0.07em",
  },
  editorShell: {
    minHeight: 316,
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    padding: "29px 30px 34px",
    fontFamily: '"Geist Mono Variable", ui-monospace, monospace',
    fontWeight: 430,
    lineHeight: 1.62,
  },
  lineNumbers: {
    margin: 0,
    padding: "0 21px 0 0",
    userSelect: "none",
    textAlign: "right",
    font: "inherit",
    lineHeight: "inherit",
    opacity: 0.72,
  },
});

export const resizeHandleStyles = stylex.create({
  handle: {
    width: 18,
    height: 92,
    position: "absolute",
    top: "50%",
    zIndex: 3,
    borderWidth: 0,
    padding: 0,
    transform: "translateY(-50%)",
    backgroundColor: "transparent",
    color: "inherit",
    cursor: "ew-resize",
    touchAction: "none",
    font: "inherit",
    "::after": {
      content: '""',
      width: 3,
      height: 38,
      position: "absolute",
      top: "50%",
      left: "50%",
      borderRadius: 999,
      opacity: 0.42,
      transform: "translate(-50%, -50%)",
      backgroundColor: "rgba(255, 255, 255, 0.72)",
      boxShadow: "0 0 0 1px rgba(0, 0, 0, 0.14)",
      transition: "height 140ms cubic-bezier(0.23, 1, 0.32, 1), opacity 140ms ease",
    },
    ":hover::after": {
      height: { "@media (hover: hover) and (pointer: fine)": 44 },
      opacity: { "@media (hover: hover) and (pointer: fine)": 0.72 },
    },
    ":active::after": { height: 48, opacity: 0.88 },
    ":focus-visible": {
      outlineWidth: 2,
      outlineStyle: "solid",
      outlineColor: "#9187d5",
      outlineOffset: -4,
    },
  },
  left: { left: 0 },
  right: { right: 0 },
});
