export const syntaxThemes = [
  { value: "github-dark-default", label: "GitHub Dark" },
  { value: "dark-plus", label: "VS Code Dark+" },
  { value: "dracula", label: "Dracula" },
  { value: "nord", label: "Nord" },
  { value: "one-dark-pro", label: "One Dark Pro" },
  { value: "tokyo-night", label: "Tokyo Night" },
  { value: "catppuccin-mocha", label: "Catppuccin Mocha" },
  { value: "rose-pine", label: "Rosé Pine" },
  { value: "github-light-default", label: "GitHub Light" },
  { value: "light-plus", label: "VS Code Light+" },
  { value: "horizon", label: "Horizon" },
  { value: "horizon-bright", label: "Horizon Bright" },
  { value: "ayu-light", label: "Ayu Light" },
  { value: "catppuccin-latte", label: "Catppuccin Latte" },
  { value: "rose-pine-dawn", label: "Rosé Pine Dawn" },
  { value: "solarized-light", label: "Solarized Light" },
  { value: "material-theme-ocean", label: "Material Ocean" },
  { value: "vitesse-light", label: "Vitesse Light" },
] as const;

export type SyntaxTheme = (typeof syntaxThemes)[number]["value"];

export const themeLoaders = {
  "github-dark-default": () => import("@shikijs/themes/github-dark-default"),
  "dark-plus": () => import("@shikijs/themes/dark-plus"),
  dracula: () => import("@shikijs/themes/dracula"),
  nord: () => import("@shikijs/themes/nord"),
  "one-dark-pro": () => import("@shikijs/themes/one-dark-pro"),
  "tokyo-night": () => import("@shikijs/themes/tokyo-night"),
  "catppuccin-mocha": () => import("@shikijs/themes/catppuccin-mocha"),
  "rose-pine": () => import("@shikijs/themes/rose-pine"),
  "github-light-default": () => import("@shikijs/themes/github-light-default"),
  "light-plus": () => import("@shikijs/themes/light-plus"),
  horizon: () => import("@shikijs/themes/horizon"),
  "horizon-bright": () => import("@shikijs/themes/horizon-bright"),
  "ayu-light": () => import("@shikijs/themes/ayu-light"),
  "catppuccin-latte": () => import("@shikijs/themes/catppuccin-latte"),
  "rose-pine-dawn": () => import("@shikijs/themes/rose-pine-dawn"),
  "solarized-light": () => import("@shikijs/themes/solarized-light"),
  "material-theme-ocean": () => import("@shikijs/themes/material-theme-ocean"),
  "vitesse-light": () => import("@shikijs/themes/vitesse-light"),
} satisfies Record<SyntaxTheme, () => Promise<unknown>>;
